
name: Android CI App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ] #puedes agregar más ramas dentro del arreglo eg: [ "main", "refactorBranch" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Build App
        run: ./gradlew assemble